language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm
install:
    - composer install --dev --no-interaction
script:
    - php bin/daedalus --version
    - php bin/daedalus lint
    - php bin/daedalus phpunit
after_script:
    - php bin/coveralls
