daedalus:
    tasks:
        build: 
            description: Creates distribution
            commands:
                package:
                    command: phar
                    arguments:
                        output: build/dist/daedalus.phar
                        compression: none
                        stub: path/to/stub.php
                        finder:
                            name: ['*.php', 'daedalus']
                            in: '.'
                            exclude: ['tests', 'vendor']
                chmod:
                    command: chmod
                    arguments:
                        file: bin/daedalus
                        mode: 0755
