daedalus:
    tasks:
        build: 
            description: Creates distribution
            commands:
                 commandOne:
                     command: chmod
                     arguments:
                        file: %project.basedir%/bin/daedalus
                        mode: +x
                 lint: { command: lint, arguments: {directory: %project.basedir%/src/**} }
                 clean: { command: clean, arguments: {directory: %project.basedir%/build/} }
