daedalus:
    tasks:
        phpunit:
            description: Runs phpunit tests
            commands:
                phpunit:
                    command: phpunit
                    options:
                        configuration: './phpunit.xml.dist'
        lint:
            description: Lint check all code
            commands:
                php_lint_check:
                    command: phplint
                    arguments:
                        source: 'src/'
        checkstyle:
            description: Runs phpcs
            commands:
                phpcs:
                    command: phpcs
                    arguments:
                        source: 'src/'
                    options:
                        report: full
                        standard: PSR1,PSR2
        build:
            description: Creates distribution
            requires: [lint, phpunit, checkstyle]
