daedalus:
    tasks:
        phpunit:
            description: Runs phpunit tests
            commands:
                phpunit:
                    command: phpunit
        lint:
            description: Lint check all code
            commands:
                lint_check:
                    command: lint
        checkstyle:
            description: Runs phpcs
            commands:
                phpcs:
                    command: phpcs
        build: 
            description: Creates distribution
            requires: [lint, phpunit, checkstyle]
            commands:
                package:
                    command: phar
                    options:
                        output: build/dist/daedalus.phar
                        compression: none
                        stub: path/to/stub.php
                        finder:
                            name: ['*.php', 'daedalus']
                            in: ['src/', 'bin/']
                            exclude: ['tests/', 'vendor/']
                chmod:
                    command: chmod
                    options:
                        file: bin/daedalus
                        mode: 0755
